# Generated by Django 2.2.1 on 2019-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babylion',
            name='part',
            field=models.BooleanField(default=True),
        ),
    ]
