# Generated by Django 2.2.1 on 2019-05-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_babylion_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babylion',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
