# Generated by Django 2.2.1 on 2019-05-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190514_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babylion',
            name='part',
            field=models.BooleanField(),
        ),
    ]
